2016-11-14 19:15:53,157 [WARNING] django.request: Not Found: /favicon.ico
2016-11-14 19:20:08,509 [WARNING] django.request: Not Found: /create_customer/
2016-11-14 19:20:08,511 [WARNING] django.request: Not Found: /create_customer/
2016-11-14 19:20:08,513 [WARNING] django.request: Not Found: /create_driver/
2016-11-14 19:20:08,514 [WARNING] django.request: Not Found: /create_driver/
2016-11-14 19:20:08,516 [WARNING] django.request: Not Found: /login/
2016-11-14 19:20:08,517 [WARNING] django.request: Not Found: /add_profile_pic/
2016-11-14 19:20:08,518 [WARNING] django.request: Not Found: /login/
2016-11-14 19:20:08,520 [WARNING] django.request: Not Found: /login/
2016-11-14 19:20:08,521 [WARNING] django.request: Not Found: /login/
2016-11-14 19:20:08,522 [ERROR] django.request: Internal Server Error: /disable_driver/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/tormodfladby/Documents/TorgeirsArbeid/GOtuk/control/views.py", line 67, in post
    user = CustomUser.objects.get(email=request.session['user_email'])
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
KeyError: 'user_email'
2016-11-14 19:23:51,918 [DEBUG] django.request: <WSGIRequest: POST '/create_customer'>
2016-11-14 19:23:52,443 [DEBUG] django.request: <WSGIRequest: POST '/create_customer'>
2016-11-14 19:23:52,645 [DEBUG] django.request: <WSGIRequest: POST '/create_driver'>
2016-11-14 19:23:52,851 [DEBUG] django.request: <WSGIRequest: POST '/create_driver'>
2016-11-14 19:23:53,902 [ERROR] django.request: Internal Server Error: /available_drivers
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view control.views.AvailabilityView didn't return an HttpResponse object. It returned None instead.
2016-11-14 19:25:06,779 [DEBUG] django.request: <WSGIRequest: POST '/create_customer'>
2016-11-14 19:25:07,338 [DEBUG] django.request: <WSGIRequest: POST '/create_customer'>
2016-11-14 19:25:07,539 [DEBUG] django.request: <WSGIRequest: POST '/create_driver'>
2016-11-14 19:25:07,758 [DEBUG] django.request: <WSGIRequest: POST '/create_driver'>
2016-11-14 19:25:28,011 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:25:59,478 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:25:59,510 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:26:49,533 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:26:49,565 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:27:50,842 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:27:50,876 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:28:14,334 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:28:14,366 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:28:47,601 [WARNING] django.request: Not Found: /media/15055642_10153813774332101_159260350940143519_n.jpg
2016-11-14 19:28:47,610 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:28:47,640 [WARNING] django.request: Not Found: /media/15055642_10153813774332101_159260350940143519_n.jpg
2016-11-14 19:28:52,501 [WARNING] django.request: Not Found: /media/profilepics/default.png
2016-11-14 19:28:52,535 [WARNING] django.request: Not Found: /media/profilepics/default.png
